// resources/js/components/announcements/CreateAnnouncement.vue
<template>
    <div class="card mb-4">
        <div class="card-header">
            Create Announcement
        </div>
        <div class="card-body">
            <div>
                <div class="form-group">
                    <label for="title">Title / Subject</label>
                    <input
                        v-model="title"
                        type="text"
                        class="form-control"
                        id="title"
                        placeholder="Enter Title"
                    >
                </div>
                <div class="form-group">
                    <vue-editor v-model="message"/>
                </div>

                <div class="form-group">
                    <label for="emails">Email Addresses (CSV) </label>
                    <textarea class="form-control" name="emails" id="emails" v-model="emails"/>
                </div>

                <div class="alert alert-info">
                    Note: If no emails are specified, by default this creates an activity feed and emails all
                    participants in the TrenchDevs account.
                </div>

                <div class="row">
                    <div class="col text-right">
                        <button class="btn btn-success" v-on:click="announce">Announce</button>
                    </div>
                </div>
            </div>

            <div class="alert alert-danger m-3" v-if="errors">
                <ul>
                    <li v-for="error in errors">{{error[0]}}</li>
                </ul>
            </div>
        </div>
    </div>
</template>

<script>
    import {VueEditor} from "vue2-editor";
    import axios from 'axios';

    export default {
        components: {
            VueEditor,
        },
        mounted() {
            console.log('component mounted...')
        },
        data() {
            return {
                title: '',
                message: "Enter email contents here..",
                errors: null,
                emails: null,
            };
        },
        methods: {
            announce() {
                const data = {
                    title: this.title,
                    message: this.message,
                    emails: this.emails || null,
                };
                axios.post('/announcements/announce', data)
                    .then((d) => {
                        window.location.href = "/announcements"
                    })
                    .catch(({response}) => {
                        const {errors} = response.data;
                        if (errors) {
                            this.errors = errors;
                        }
                    });
            }
        }
    }
</script>

// backend/resources/js/Themes/TrenchDevsAdmin/Pages/Announcements/CreateAnnouncement.jsx
import Card from "@/Themes/TrenchDevsAdmin/Components/Card";
import FormInput from "@/Themes/TrenchDevsAdmin/Components/Forms/FormInput";
import {useForm} from "@inertiajs/inertia-react";
import TrenchDevsAdminLayout from "@/Themes/TrenchDevsAdmin/Layouts/TrenchDevsAdminLayout";

export default function CreateAnnouncement() {

    const announcementForm = useForm({
        'title': '',
        'message': '',
        'emails': '',
    });

    function onSubmit() {
        announcementForm.post('/dashboard/announcements/create');
    }

    return (
        <TrenchDevsAdminLayout>
            <Card header={"Create Announcement"}>
                <div>
                    <div className="form-group">
                        <label htmlFor="title">Title / Subject</label>
                        <FormInput
                            name={"title"}
                            className={"form-control"}
                            form={announcementForm}
                            type={"input"}
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="message">Message</label>
                        <FormInput
                            name={"message"}
                            form={announcementForm}
                            type={"rich-text-editor"}
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="emails">Email Addresses (CSV) </label>
                        <FormInput
                            className={"form-control"}
                            name={"emails"}
                            form={announcementForm}
                            type={"textarea"}
                        />
                    </div>

                    <div className="alert alert-info">
                        Note: If no emails are specified, by default this creates an activity feed and emails all
                        participants in the TrenchDevs account.
                    </div>

                    <div className="row">
                        <div className="col text-right">
                            <button className="btn btn-success" onClick={onSubmit}>Announce</button>
                        </div>
                    </div>
                </div>
            </Card>
        </TrenchDevsAdminLayout>
    );
}
